package com.spoors.beans;

import java.io.Serializable;

import org.springframework.stereotype.Component;

@Component
public class Constants implements Serializable{
	
	private String rootEmpKey="rootEmp";
	
	public static final int FORM_FIELD_TYPE_TEXT = 1;
	public static final int FORM_FIELD_TYPE_NUMBER = 2;
	public static final int FORM_FIELD_TYPE_DATE = 3;
	public static final int FORM_FIELD_TYPE_YES_NO = 4;
	public static final int FORM_FIELD_TYPE_SINGLE_SELECT_LIST = 5;
	public static final int FORM_FIELD_TYPE_MULTI_SELECT_LIST = 6;

	public static final int FORM_FIELD_TYPE_CUSTOMER = 7;
	public static final int FORM_FIELD_TYPE_EMAIL = 8;
	public static final int FORM_FIELD_TYPE_PHONE = 9;
	public static final int FORM_FIELD_TYPE_URL = 10;
	public static final int FORM_FIELD_TYPE_TIME = 11;
	public static final int FORM_FIELD_TYPE_IMAGE = 12;
	public static final int FORM_FIELD_TYPE_SIGNATURE = 13;
	public static final int FORM_FIELD_TYPE_LIST = 14;
	public static final int FORM_FIELD_TYPE_EMPLOYEE = 15;
	public static final int FORM_FIELD_TYPE_CURRENCY = 16;
	public static final int FORM_FIELD_TYPE_MULTIPICK_LIST = 17;
	public static final int FORM_FIELD_TYPE_LOCATION = 18;
	public static final int FORM_FIELD_TYPE_DATE_TIME = 19;
	public static final int FORM_FIELD_TYPE_COUNTRY = 20;
	public static final int FORM_FIELD_TYPE_FINGER_PRINT = 21;
	public static final int FORM_FIELD_TYPE_AUDIO = 22;
	public static final int FORM_FIELD_TYPE_NUMBER_TO_WORD = 23;
	public static final int FORM_FIELD_TYPE_CUSTOMER_TYPE = 24;
	public static final int FORM_FIELD_TYPE_FORM = 25;
	public static final int FORM_FIELD_TYPE_TIMESPAN = 26;
	public static final int FORM_FIELD_TYPE_VIDEO = 27;
	public static final int FORM_FIELD_TYPE_AUTOGENERATED = 28;
	public static final int FORM_FIELD_TYPE_LABEL = 29;
	public static final int FORM_FIELD_TYPE_MULTIPICK_CUSTOMER = 30;
	public static final int FORM_FIELD_TYPE_TERRITORY = 31;
	public static final int FORM_FIELD_TYPE_CUSTOM_ENTITY = 32;
	public static final int FORM_FIELD_TYPE_MULTI_MEDIA = 33;

	public static final int FORM_FIELD_TYPE_MONTH = 34;
	public static final int FORM_FIELD_TYPE_RICH_TEXT_FORMAT = 35;
	public static final int TYPE_CURRENT_MONTH = -100;
	
	public static final int FORM_FIELD_TYPE_RICH_TEXT = 35;

	public String getRootEmpKey() {
		return rootEmpKey;
	}

	public void setRootEmpKey(String rootEmpKey) {
		this.rootEmpKey = rootEmpKey;
	}
	
	

}
